project_id = "iokwqxhhpblcbkrxgcje"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.sync-qogita-brands]
    verify_jwt = false
  [functions.sync-qogita-categories]
    verify_jwt = false
  [functions.sync-qogita-products]
    verify_jwt = false
  [functions.sync-qogita-offers-detail]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.sync-meilisearch]
    verify_jwt = false
  [functions.run-sync-pipeline]
    verify_jwt = false
  [functions.test-qogita-offers]
    verify_jwt = false
