ALTER TABLE public.offers DISABLE TRIGGER trg_offers_update_product_aggregates;
ALTER TABLE public.offers DISABLE TRIGGER trg_offers_update_product_country_stats;
ALTER TABLE public.offers DISABLE TRIGGER trg_update_product_aggregates;
ALTER TABLE public.offers DISABLE TRIGGER trg_update_product_country_stats;