-- Function to get accurate product counts per category
CREATE OR REPLACE FUNCTION count_products_per_category()
RETURNS TABLE(category_id uuid, product_count bigint)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  SELECT p.category_id, COUNT(*) as product_count
  FROM products p
  WHERE p.is_active = true AND p.offer_count > 0 AND p.category_id IS NOT NULL
  GROUP BY p.category_id;
$$;

-- Batch translate category names to French
UPDATE categories SET name_fr = CASE name
  WHEN 'Accessories' THEN 'Accessoires'
  WHEN 'Acne' THEN 'Acné'
  WHEN 'After Sun' THEN 'Après-soleil'
  WHEN 'Aftershave' THEN 'Après-rasage'
  WHEN 'Aftersun' THEN 'Après-soleil'
  WHEN 'All-Purpose Cleaners' THEN 'Nettoyants multi-usages'
  WHEN 'Alternative Medicine' THEN 'Médecine alternative'
  WHEN 'Ampoules' THEN 'Ampoules'
  WHEN 'Animal & Pet Repellents' THEN 'Répulsifs animaux'
  WHEN 'Anti-Aging' THEN 'Anti-âge'
  WHEN 'Anti-Aging Facial Care' THEN 'Soin visage anti-âge'
  WHEN 'Anti-Aging Mask' THEN 'Masque anti-âge'
  WHEN 'Anti-Aging Serum' THEN 'Sérum anti-âge'
  WHEN 'Anti-Cellulite' THEN 'Anti-cellulite'
  WHEN 'Anti-Dandruff' THEN 'Anti-pelliculaire'
  WHEN 'Anti-Frizz' THEN 'Anti-frisottis'
  WHEN 'Anti-Pigmentation Spot Cream' THEN 'Crème anti-taches'
  WHEN 'Anti-Pimple Mask' THEN 'Masque anti-boutons'
  WHEN 'Anti-Stretch Mark Cream' THEN 'Crème anti-vergetures'
  WHEN 'Antiseptics & Cleaning Supplies' THEN 'Antiseptiques & nettoyants'
  WHEN 'Applicators' THEN 'Applicateurs'
  WHEN 'Aromatherapy & Essential Oils' THEN 'Aromathérapie & huiles essentielles'
  WHEN 'Artificial Nails & Nail Decoration' THEN 'Faux ongles & décoration'
  WHEN 'Attachment Brushes' THEN 'Brosses accessoires'
  WHEN 'Baby & Child' THEN 'Bébé & enfant'
  WHEN 'Baby & Child Accessories' THEN 'Accessoires bébé & enfant'
  WHEN 'Baby Bath' THEN 'Bain bébé'
  WHEN 'Baby Cream & Oil' THEN 'Crème & huile bébé'
  WHEN 'Baby Scissors' THEN 'Ciseaux bébé'
  WHEN 'Baby Shampoo' THEN 'Shampooing bébé'
  WHEN 'Baby Shower Gel & Soap' THEN 'Gel douche & savon bébé'
  WHEN 'Baby Wipes & Diapers' THEN 'Lingettes & couches bébé'
  WHEN 'Bandage Material' THEN 'Matériel de bandage'
  WHEN 'Base Coat' THEN 'Base coat'
  WHEN 'Bath Foam' THEN 'Mousse de bain'
  WHEN 'Bath Oil & Bath Milk' THEN 'Huile & lait de bain'
  WHEN 'Bath Salts & Bath Bombs' THEN 'Sels & bombes de bain'
  WHEN 'Bath Sponges, Brushes & Loofas' THEN 'Éponges & brosses de bain'
  WHEN 'Bb Cream & Cc Cream' THEN 'BB Crème & CC Crème'
  WHEN 'Beard Care' THEN 'Soin de la barbe'
  WHEN 'Beard Care Accessories' THEN 'Accessoires soin barbe'
  WHEN 'Beard Care Sets' THEN 'Coffrets soin barbe'
  WHEN 'Beauty Tools' THEN 'Outils de beauté'
  WHEN 'Biometric Monitors & Accessories' THEN 'Moniteurs biométriques'
  WHEN 'Blackhead Masks' THEN 'Masques points noirs'
  WHEN 'Bladder, Kidneys & Prostate' THEN 'Vessie, reins & prostate'
  WHEN 'Bleach' THEN 'Eau de Javel'
  WHEN 'Bleaching' THEN 'Blanchiment'
  WHEN 'Blotting Papers' THEN 'Papiers matifiants'
  WHEN 'Blush' THEN 'Blush'
  WHEN 'Body Butter' THEN 'Beurre corporel'
  WHEN 'Body Care' THEN 'Soin du corps'
  WHEN 'Body Care Sets' THEN 'Coffrets soin du corps'
  WHEN 'Body Cream & Body Lotion' THEN 'Crème & lotion corporelle'
  WHEN 'Body Oil' THEN 'Huile corporelle'
  WHEN 'Body Peeling' THEN 'Gommage corporel'
  WHEN 'Body Powder' THEN 'Poudre corporelle'
  WHEN 'Body Spray & Body Mist' THEN 'Brume corporelle'
  WHEN 'Bones & Joints' THEN 'Os & articulations'
  WHEN 'Bronzer' THEN 'Bronzeur'
  WHEN 'Brow Gel & Brow Wax' THEN 'Gel & cire sourcils'
  WHEN 'Brow Pencils & Brow Powder' THEN 'Crayons & poudre sourcils'
  WHEN 'Brushes' THEN 'Brosses'
  WHEN 'Bubble Bath' THEN 'Bain moussant'
  WHEN 'Candles & Home Fragrance' THEN 'Bougies & parfums intérieur'
  WHEN 'Cleanser' THEN 'Nettoyant'
  WHEN 'Cold, Flu & Allergies' THEN 'Rhume, grippe & allergies'
  WHEN 'Cologne' THEN 'Eau de Cologne'
  WHEN 'Colour Corrector' THEN 'Correcteur de teint'
  WHEN 'Combs' THEN 'Peignes'
  WHEN 'Concealer' THEN 'Anti-cernes'
  WHEN 'Conditioner' THEN 'Après-shampooing'
  WHEN 'Contact Lens Solution & Eye Drops' THEN 'Solution lentilles & gouttes'
  WHEN 'Contour' THEN 'Contour'
  WHEN 'Cotton & Cotton Swabs' THEN 'Coton & cotons-tiges'
  WHEN 'Cuticle Care' THEN 'Soin des cuticules'
  WHEN 'Day Cream' THEN 'Crème de jour'
  WHEN 'Dental Floss' THEN 'Fil dentaire'
  WHEN 'Deodorant' THEN 'Déodorant'
  WHEN 'Depilatory Cream & Wax' THEN 'Crème & cire dépilatoire'
  WHEN 'Detergent' THEN 'Lessive'
  WHEN 'Dietary Supplements' THEN 'Compléments alimentaires'
  WHEN 'Digestion' THEN 'Digestion'
  WHEN 'Dishwasher Detergent' THEN 'Détergent lave-vaisselle'
  WHEN 'Disinfection' THEN 'Désinfection'
  WHEN 'Eau De Parfum' THEN 'Eau de parfum'
  WHEN 'Eau De Toilette' THEN 'Eau de toilette'
  WHEN 'Electric Razor & Trimmer' THEN 'Rasoir & tondeuse électrique'
  WHEN 'Eye Brush' THEN 'Pinceau yeux'
  WHEN 'Eye Cream' THEN 'Crème yeux'
  WHEN 'Eye Liner' THEN 'Eye-liner'
  WHEN 'Eye Make-Up Remover' THEN 'Démaquillant yeux'
  WHEN 'Eye Mask' THEN 'Masque yeux'
  WHEN 'Eye Primer & Eye Base' THEN 'Base yeux'
  WHEN 'Eye Serum' THEN 'Sérum yeux'
  WHEN 'Eye Shadow' THEN 'Ombre à paupières'
  WHEN 'Eyebrow Care' THEN 'Soin des sourcils'
  WHEN 'Eyelash Curler' THEN 'Recourbe-cils'
  WHEN 'Eyelash Serum' THEN 'Sérum cils'
  WHEN 'Face Brush' THEN 'Brosse visage'
  WHEN 'Face Mask' THEN 'Masque visage'
  WHEN 'Face Wash & Cleanser' THEN 'Nettoyant visage'
  WHEN 'Facial Care' THEN 'Soin visage'
  WHEN 'Facial Care Sets' THEN 'Coffrets soin visage'
  WHEN 'Facial Serum' THEN 'Sérum visage'
  WHEN 'Facial Toner' THEN 'Lotion tonique visage'
  WHEN 'False Eyelashes' THEN 'Faux cils'
  WHEN 'Feminine Wash' THEN 'Hygiène intime'
  WHEN 'First Aid & Medical Supplies' THEN 'Premiers secours & matériel médical'
  WHEN 'Fixation & Styling' THEN 'Fixation & coiffage'
  WHEN 'Foot Care' THEN 'Soin des pieds'
  WHEN 'Foundation' THEN 'Fond de teint'
  WHEN 'Fragrance' THEN 'Parfum'
  WHEN 'Fragrance Sets' THEN 'Coffrets parfum'
  WHEN 'Gift Sets' THEN 'Coffrets cadeaux'
  WHEN 'Hair Accessories' THEN 'Accessoires cheveux'
  WHEN 'Hair Care' THEN 'Soin capillaire'
  WHEN 'Hair Care Sets' THEN 'Coffrets soin capillaire'
  WHEN 'Hair Colour' THEN 'Coloration capillaire'
  WHEN 'Hair Dryer' THEN 'Sèche-cheveux'
  WHEN 'Hair Mask' THEN 'Masque capillaire'
  WHEN 'Hair Oil & Hair Serum' THEN 'Huile & sérum capillaire'
  WHEN 'Hair Removal' THEN 'Épilation'
  WHEN 'Hair Straightener & Curling Iron' THEN 'Lisseur & fer à boucler'
  WHEN 'Hair Styling' THEN 'Coiffage'
  WHEN 'Hand Care' THEN 'Soin des mains'
  WHEN 'Hand Cream' THEN 'Crème mains'
  WHEN 'Hand Sanitiser' THEN 'Gel hydroalcoolique'
  WHEN 'Hand Soap' THEN 'Savon mains'
  WHEN 'Hand Wash' THEN 'Lavage des mains'
  WHEN 'Health & Well-being' THEN 'Santé & bien-être'
  WHEN 'Highlighter' THEN 'Enlumineur'
  WHEN 'Home & Household' THEN 'Maison & ménage'
  WHEN 'Household' THEN 'Ménage'
  WHEN 'Immunity & Energy' THEN 'Immunité & énergie'
  WHEN 'Incontinence' THEN 'Incontinence'
  WHEN 'Insect Repellent' THEN 'Anti-moustiques'
  WHEN 'Leave-In Hair Conditioner' THEN 'Soin sans rinçage'
  WHEN 'Lip Balm & Lip Care' THEN 'Baume & soin lèvres'
  WHEN 'Lip Brush' THEN 'Pinceau lèvres'
  WHEN 'Lip Gloss' THEN 'Gloss'
  WHEN 'Lip Liner' THEN 'Crayon lèvres'
  WHEN 'Lip Primer' THEN 'Base lèvres'
  WHEN 'Lipstick' THEN 'Rouge à lèvres'
  WHEN 'Make-Up' THEN 'Maquillage'
  WHEN 'Make-Up Accessories' THEN 'Accessoires maquillage'
  WHEN 'Make-Up Remover' THEN 'Démaquillant'
  WHEN 'Make-Up Sets' THEN 'Coffrets maquillage'
  WHEN 'Manicure & Pedicure' THEN 'Manucure & pédicure'
  WHEN 'Mascara' THEN 'Mascara'
  WHEN 'Medical Devices' THEN 'Dispositifs médicaux'
  WHEN 'Micellar Water' THEN 'Eau micellaire'
  WHEN 'Moisturiser' THEN 'Hydratant'
  WHEN 'Mouthwash' THEN 'Bain de bouche'
  WHEN 'Nail Care' THEN 'Soin des ongles'
  WHEN 'Nail Care Sets' THEN 'Coffrets soin ongles'
  WHEN 'Nail File' THEN 'Lime à ongles'
  WHEN 'Nail Polish' THEN 'Vernis à ongles'
  WHEN 'Nail Polish Remover' THEN 'Dissolvant'
  WHEN 'Night Cream' THEN 'Crème de nuit'
  WHEN 'Oral Care' THEN 'Hygiène bucco-dentaire'
  WHEN 'Oral Care Sets' THEN 'Coffrets hygiène bucco-dentaire'
  WHEN 'Other' THEN 'Autres'
  WHEN 'Others' THEN 'Autres'
  WHEN 'Pain Relief & Muscle Pain' THEN 'Anti-douleur & douleurs musculaires'
  WHEN 'Perfume' THEN 'Parfum'
  WHEN 'Personal Care' THEN 'Soins personnels'
  WHEN 'Pet Care' THEN 'Soin des animaux'
  WHEN 'Powder' THEN 'Poudre'
  WHEN 'Pre-shave & Shaving Cream' THEN 'Pré-rasage & crème de rasage'
  WHEN 'Primer' THEN 'Primer'
  WHEN 'Razor & Blades' THEN 'Rasoir & lames'
  WHEN 'Sanitary Towels & Tampons' THEN 'Serviettes & tampons'
  WHEN 'Scalp Care' THEN 'Soin cuir chevelu'
  WHEN 'Self Tanning' THEN 'Autobronzant'
  WHEN 'Setting Spray' THEN 'Spray fixateur'
  WHEN 'Sexual Health' THEN 'Santé sexuelle'
  WHEN 'Shampoo' THEN 'Shampooing'
  WHEN 'Shaving & Beard' THEN 'Rasage & barbe'
  WHEN 'Shower Gel' THEN 'Gel douche'
  WHEN 'Skin Care' THEN 'Soin de la peau'
  WHEN 'Sleep & Relaxation' THEN 'Sommeil & relaxation'
  WHEN 'Soap' THEN 'Savon'
  WHEN 'Soap & Lotion Dispensers' THEN 'Distributeurs savon & lotion'
  WHEN 'Sponges' THEN 'Éponges'
  WHEN 'Styling Tools & Accessories' THEN 'Outils & accessoires coiffage'
  WHEN 'Sun Protection' THEN 'Protection solaire'
  WHEN 'Sunscreen' THEN 'Crème solaire'
  WHEN 'Tissues' THEN 'Mouchoirs'
  WHEN 'Toilet Paper' THEN 'Papier toilette'
  WHEN 'Toothbrush' THEN 'Brosse à dents'
  WHEN 'Toothpaste' THEN 'Dentifrice'
  WHEN 'Top Coat' THEN 'Top coat'
  WHEN 'Tweezers' THEN 'Pince à épiler'
  WHEN 'Vitamins & Minerals' THEN 'Vitamines & minéraux'
  WHEN 'Washing-Up Detergent & Soap' THEN 'Liquide vaisselle & savon'
  WHEN 'Weight Management' THEN 'Gestion du poids'
  WHEN 'Wipes' THEN 'Lingettes'
  ELSE name
END
WHERE name_fr IS NULL;