-- Switch savings-reports bucket to private (signed URLs only)
update storage.buckets set public = false where id = 'savings-reports';

drop policy if exists "savings-reports public read" on storage.objects;

-- Only admins can list/read directly; end-users access via signed URL generated by edge function
create policy "savings-reports admin read"
  on storage.objects for select to authenticated
  using (bucket_id = 'savings-reports' and public.is_admin(auth.uid()));